wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1636273543
    t:
      1:
      - 1
      - 5
      3:
      - 16
      4: 3.6.8
      5: 0.12.6
      8:
      - 3
      - 5
early_stopping:
  desc: null
  value: 50
episode:
  desc: null
  value: 50
fn:
  desc: null
  value: -5
fp:
  desc: null
  value: -10
gamma:
  desc: null
  value: 0.99
log_results:
  desc: null
  value: ./log/train/results/_test_3
log_weights:
  desc: null
  value: ./log/train/weights/_test_3
lr:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 52
tl:
  desc: null
  value: 0
tn:
  desc: null
  value: 6
tp:
  desc: null
  value: 2
