wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1636272415
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.6.8
      5: 0.12.6
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 100
channels_one:
  desc: null
  value: 16
channels_two:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 2
fn:
  desc: null
  value: -10
fp:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.001
tn:
  desc: null
  value: 8
tp:
  desc: null
  value: 6
